// Generated by the Supabase MCP `generate_typescript_types` tool against
// the `grimoire` project (ref zvbpnxjpbecyahylhaar) after migrations
// 0001–0007 (journal v1 + advisor fixes + The Black Road import, which
// added characters/npcs/factions/quests/treasure + per-character color
// + the end_session command + the roll_dice command). Do not hand-edit
// — regenerate after any schema change and commit the diff alongside
// the migration that caused it, per CLAUDE.md's "never let schema and
// migrations drift" rule.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: '14.15'
  }
  public: {
    Tables: {
      campaign_events: {
        Row: {
          actor: string
          campaign_id: string
          created_at: string
          id: string
          kind: string
          payload: Json
        }
        Insert: {
          actor: string
          campaign_id: string
          created_at?: string
          id?: string
          kind: string
          payload?: Json
        }
        Update: {
          actor?: string
          campaign_id?: string
          created_at?: string
          id?: string
          kind?: string
          payload?: Json
        }
        Relationships: [
          {
            foreignKeyName: 'campaign_events_campaign_id_fkey'
            columns: ['campaign_id']
            isOneToOne: false
            referencedRelation: 'campaigns'
            referencedColumns: ['id']
          },
        ]
      }
      campaign_members: {
        Row: {
          campaign_id: string
          id: string
          joined_at: string
          role: string
          user_id: string
        }
        Insert: {
          campaign_id: string
          id?: string
          joined_at?: string
          role?: string
          user_id: string
        }
        Update: {
          campaign_id?: string
          id?: string
          joined_at?: string
          role?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'campaign_members_campaign_id_fkey'
            columns: ['campaign_id']
            isOneToOne: false
            referencedRelation: 'campaigns'
            referencedColumns: ['id']
          },
        ]
      }
      campaigns: {
        Row: {
          created_at: string
          id: string
          name: string
          owner: string
          system: string
        }
        Insert: {
          created_at?: string
          id?: string
          name: string
          owner: string
          system?: string
        }
        Update: {
          created_at?: string
          id?: string
          name?: string
          owner?: string
          system?: string
        }
        Relationships: []
      }
      characters: {
        Row: {
          abilities: Json
          ac: number
          alignment_title: string | null
          background: string | null
          campaign_id: string
          class_title: string
          color: string | null
          created_at: string
          gear_current: number | null
          gear_max: number | null
          gold: Json
          hp_current: number
          hp_max: number
          id: string
          level: number
          member_id: string | null
          name: string
          sheet: Json
          status: string
          xp_current: number
          xp_needed: number
        }
        Insert: {
          abilities?: Json
          ac: number
          alignment_title?: string | null
          background?: string | null
          campaign_id: string
          class_title: string
          color?: string | null
          created_at?: string
          gear_current?: number | null
          gear_max?: number | null
          gold?: Json
          hp_current: number
          hp_max: number
          id?: string
          level?: number
          member_id?: string | null
          name: string
          sheet?: Json
          status?: string
          xp_current?: number
          xp_needed?: number
        }
        Update: {
          abilities?: Json
          ac?: number
          alignment_title?: string | null
          background?: string | null
          campaign_id?: string
          class_title?: string
          color?: string | null
          created_at?: string
          gear_current?: number | null
          gear_max?: number | null
          gold?: Json
          hp_current?: number
          hp_max?: number
          id?: string
          level?: number
          member_id?: string | null
          name?: string
          sheet?: Json
          status?: string
          xp_current?: number
          xp_needed?: number
        }
        Relationships: [
          {
            foreignKeyName: 'characters_campaign_id_fkey'
            columns: ['campaign_id']
            isOneToOne: false
            referencedRelation: 'campaigns'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'characters_member_id_fkey'
            columns: ['member_id']
            isOneToOne: false
            referencedRelation: 'campaign_members'
            referencedColumns: ['id']
          },
        ]
      }
      factions: {
        Row: {
          campaign_id: string
          created_at: string
          disposition: string | null
          goal: string | null
          id: string
          leader: string | null
          name: string
          notes: string | null
          status: string | null
          territory: string | null
          type: string | null
        }
        Insert: {
          campaign_id: string
          created_at?: string
          disposition?: string | null
          goal?: string | null
          id?: string
          leader?: string | null
          name: string
          notes?: string | null
          status?: string | null
          territory?: string | null
          type?: string | null
        }
        Update: {
          campaign_id?: string
          created_at?: string
          disposition?: string | null
          goal?: string | null
          id?: string
          leader?: string | null
          name?: string
          notes?: string | null
          status?: string | null
          territory?: string | null
          type?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'factions_campaign_id_fkey'
            columns: ['campaign_id']
            isOneToOne: false
            referencedRelation: 'campaigns'
            referencedColumns: ['id']
          },
        ]
      }
      journal_entries: {
        Row: {
          actor_color: string | null
          actor_name: string
          author: string
          body: string
          campaign_id: string
          created_at: string
          id: string
          kind: string
          session_id: string
        }
        Insert: {
          actor_color?: string | null
          actor_name: string
          author: string
          body: string
          campaign_id: string
          created_at?: string
          id?: string
          kind: string
          session_id: string
        }
        Update: {
          actor_color?: string | null
          actor_name?: string
          author?: string
          body?: string
          campaign_id?: string
          created_at?: string
          id?: string
          kind?: string
          session_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'journal_entries_campaign_id_fkey'
            columns: ['campaign_id']
            isOneToOne: false
            referencedRelation: 'campaigns'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'journal_entries_session_id_fkey'
            columns: ['session_id']
            isOneToOne: false
            referencedRelation: 'sessions'
            referencedColumns: ['id']
          },
        ]
      }
      npcs: {
        Row: {
          attitude: string | null
          campaign_id: string
          created_at: string
          hire_terms: string | null
          id: string
          is_hireling: boolean
          location: string | null
          name: string
          role: string | null
          stat_block: Json | null
          status: string
          summary: string
        }
        Insert: {
          attitude?: string | null
          campaign_id: string
          created_at?: string
          hire_terms?: string | null
          id?: string
          is_hireling?: boolean
          location?: string | null
          name: string
          role?: string | null
          stat_block?: Json | null
          status?: string
          summary?: string
        }
        Update: {
          attitude?: string | null
          campaign_id?: string
          created_at?: string
          hire_terms?: string | null
          id?: string
          is_hireling?: boolean
          location?: string | null
          name?: string
          role?: string | null
          stat_block?: Json | null
          status?: string
          summary?: string
        }
        Relationships: [
          {
            foreignKeyName: 'npcs_campaign_id_fkey'
            columns: ['campaign_id']
            isOneToOne: false
            referencedRelation: 'campaigns'
            referencedColumns: ['id']
          },
        ]
      }
      quests: {
        Row: {
          campaign_id: string
          claimant: string | null
          code: string
          created_at: string
          goal: string | null
          id: string
          sort_order: number
          status: string
          summary: string
          title: string
        }
        Insert: {
          campaign_id: string
          claimant?: string | null
          code: string
          created_at?: string
          goal?: string | null
          id?: string
          sort_order?: number
          status: string
          summary?: string
          title: string
        }
        Update: {
          campaign_id?: string
          claimant?: string | null
          code?: string
          created_at?: string
          goal?: string | null
          id?: string
          sort_order?: number
          status?: string
          summary?: string
          title?: string
        }
        Relationships: [
          {
            foreignKeyName: 'quests_campaign_id_fkey'
            columns: ['campaign_id']
            isOneToOne: false
            referencedRelation: 'campaigns'
            referencedColumns: ['id']
          },
        ]
      }
      sessions: {
        Row: {
          campaign_id: string
          ended_at: string | null
          id: string
          number: number
          started_at: string
          title: string | null
        }
        Insert: {
          campaign_id: string
          ended_at?: string | null
          id?: string
          number: number
          started_at?: string
          title?: string | null
        }
        Update: {
          campaign_id?: string
          ended_at?: string | null
          id?: string
          number?: number
          started_at?: string
          title?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'sessions_campaign_id_fkey'
            columns: ['campaign_id']
            isOneToOne: false
            referencedRelation: 'campaigns'
            referencedColumns: ['id']
          },
        ]
      }
      treasure: {
        Row: {
          campaign_id: string
          category: string | null
          created_at: string
          held_by: string | null
          id: string
          location: string | null
          name: string
          notes: string | null
          quantity_value: string | null
          status: string | null
        }
        Insert: {
          campaign_id: string
          category?: string | null
          created_at?: string
          held_by?: string | null
          id?: string
          location?: string | null
          name: string
          notes?: string | null
          quantity_value?: string | null
          status?: string | null
        }
        Update: {
          campaign_id?: string
          category?: string | null
          created_at?: string
          held_by?: string | null
          id?: string
          location?: string | null
          name?: string
          notes?: string | null
          quantity_value?: string | null
          status?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'treasure_campaign_id_fkey'
            columns: ['campaign_id']
            isOneToOne: false
            referencedRelation: 'campaigns'
            referencedColumns: ['id']
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      amend_journal_entry: {
        Args: { p_entry_id: string; p_new_body: string }
        Returns: {
          actor_color: string | null
          actor_name: string
          author: string
          body: string
          campaign_id: string
          created_at: string
          id: string
          kind: string
          session_id: string
        }
        SetofOptions: {
          from: '*'
          to: 'journal_entries'
          isOneToOne: true
          isSetofReturn: false
        }
      }
      create_campaign: {
        Args: { p_name: string }
        Returns: {
          created_at: string
          id: string
          name: string
          owner: string
          system: string
        }
        SetofOptions: {
          from: '*'
          to: 'campaigns'
          isOneToOne: true
          isSetofReturn: false
        }
      }
      end_session: {
        Args: { p_campaign_id: string }
        Returns: {
          campaign_id: string
          ended_at: string | null
          id: string
          number: number
          started_at: string
          title: string | null
        }
        SetofOptions: {
          from: '*'
          to: 'sessions'
          isOneToOne: true
          isSetofReturn: false
        }
      }
      log_journal_entry: {
        Args: {
          p_actor_color?: string
          p_actor_name: string
          p_body: string
          p_campaign_id: string
          p_kind: string
          p_session_id: string
        }
        Returns: {
          actor_color: string | null
          actor_name: string
          author: string
          body: string
          campaign_id: string
          created_at: string
          id: string
          kind: string
          session_id: string
        }
        SetofOptions: {
          from: '*'
          to: 'journal_entries'
          isOneToOne: true
          isSetofReturn: false
        }
      }
      roll_dice: {
        Args: {
          p_campaign_id: string
          p_count?: number
          p_die: string
          p_mode?: string
        }
        Returns: Json
      }
      start_session: {
        Args: { p_campaign_id: string; p_title?: string }
        Returns: {
          campaign_id: string
          ended_at: string | null
          id: string
          number: number
          started_at: string
          title: string | null
        }
        SetofOptions: {
          from: '*'
          to: 'sessions'
          isOneToOne: true
          isSetofReturn: false
        }
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, 'public'>]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables'] &
        DefaultSchema['Views'])
    ? (DefaultSchema['Tables'] &
        DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema['Tables']
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema['Tables']
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema['Enums']
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
    ? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema['CompositeTypes']
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes']
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes'][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema['CompositeTypes']
    ? DefaultSchema['CompositeTypes'][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
